name: Block Push to Main

on:
  push:
    branches:
      - main

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - name: Check user
        run: |
          if [ "${{ github.actor }}" != "leaox77" ]; then
            echo "🚫 Push directo a main prohibido. Usa Pull Requests."
            exit 1
          else
            echo "✅ Push permitido para admin (${GITHUB_ACTOR})"
          fi
